PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

CONSTRUCT {
?station geo:lat ?lat ;
    geo:long ?long .
}
WHERE {
  ?station a schema:CivicStructure ;
    <http://example.org/latlong> ?latlong .
  
    BIND(strbefore(?latlong, ",") as ?lat) 
    BIND(replace(strafter(?latlong, ","),"^ +","") as ?long) 
}